stages:
  - build
  - test
  - deploy

build:
  image: docker:20
  script:
    - docker-compose build

test:
  image: docker:20
  script:
    - docker-compose up -d
    - docker-compose exec app npm test

deploy:
  image: docker:20
  script:
    - docker-compose up -d
